// Strips fields a client must never be able to set from a request body before it's spread into a
// Prisma `create`/`update`. Several user-owned routers do `data: { ...req.body, userId }` — `userId`
// is overridden, but system-managed ledger fields and auto-detection tombstones were passing
// straight through. The 2026-09-03 audit flagged this: e.g. `PUT /lending/:id { amountRepaid: 0 }`
// rewinds the repayment ledger, `PUT /recurring/:id { autoDetected: false, dismissedAt: null }`
// un-tombstones a dismissed EMI so the next SMS scan re-creates it.
//
// Deliberately a NARROW denylist, not an allowlist:
//  - it can't break a client sending a legitimate field (the app relies on `...req.body` for a lot,
//    incl. client-generated `id`s on lending/goals/wishlist/investments — those stay);
//  - `userId` is already overridden by every call site, so it's not listed here;
//  - `active` / `status` / dates that a user legitimately manages on their own row stay allowed —
//    a user soft-deleting or re-opening their own row is not a privilege boundary.
// Only fields that are computed/managed server-side and would corrupt state if forged are removed.
const SERVER_MANAGED = new Set([
  "active", // soft-delete is a dedicated DELETE route on every model; never set via a create/update body
  "amountRepaid", // LentMoney — recomputed from the repayment ledger
  "autoGenerated", // TodoItem — set only by the Smart Action Engine
  "autoDetected", // RecurringPayment — set only by the SMS-scan upsert
  "detectedCount",
  "firstDetectedAt",
  "dismissedAt",
  "convertedLoanId",
  "createdAt",
  "updatedAt",
  // relation payloads — a nested write here is never intended
  "repayments",
  "installments",
  "billPayments",
  "provider",
  "user",
]);

// Returns `any` deliberately — the call site spreads this into a Prisma `data:` and relies on
// Prisma's own type checking for the required-field / shape guarantees (same as the `...req.body`
// it replaces). Narrowing here to `Record<string, unknown>` would make every `create` fail to
// type-check for missing required fields.
export function sanitizeBody(body: unknown): any {
  const out: Record<string, unknown> = {};
  for (const [k, v] of Object.entries((body as Record<string, unknown>) ?? {})) {
    if (!SERVER_MANAGED.has(k)) out[k] = v;
  }
  return out;
}
