-- AlterTable
ALTER TABLE `Device` ADD COLUMN `appVersionCode` INTEGER NULL,
    ADD COLUMN `appVersionName` VARCHAR(191) NULL,
    ADD COLUMN `lastSeenAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);
