-- AlterTable
ALTER TABLE `BugReport` ADD COLUMN `coinsAwarded` INTEGER NULL;

-- AlterTable
ALTER TABLE `CoinLedgerEntry` MODIFY `reason` ENUM('REFERRAL_BONUS', 'VOUCHER_REDEMPTION', 'ADMIN_ADJUSTMENT', 'BILL_PAYMENT_BONUS', 'FEEDBACK_BONUS', 'BUG_REPORT_BONUS') NOT NULL;
